### ISSUE TITLE
Suggest Human-Authored Follow-Up Questions

### ISSUE THREAD

**Issue by FraserLee** [StampyAI/stampy-chat#16]
As mentioned on the call, if there's a good follow-up question in the Stampy database, we should suggest the user ask it. 

**-- Things that need to be decided --**

Format of the question:
- *do we suggest one follow-up? multiple?*
- *do we rephrase existing database questions to sound more appropriate as a followup?* 
- *do we always suggest something, or only when it \*feels right\* in conversation?*

Format of the answer:
- *do we link externally to stampy, or reply with the answer in-chat?*
- *how do we visually differentiate chatbot and authored content?*
- *how should the prompt look so people can ask followups with the chatbot responding in the right tone / person?*

Etc:
- *how does this integrate with citation? What happens if we cite a stampy answer?*

**Comment by plexish** [comment]
quick takes on some of these:
>do we suggest one follow-up? multiple?
weak probably, when they fit?

> do we rephrase existing database questions to sound more appropriate as a followup?
probably no?

> do we always suggest something, or only when it *feels right* in conversation?
test and see whether it feels jarring more than very rarely

> do we link externally to stampy, or reply with the answer in-chat?
in chat, for sure.

> how do we visually differentiate chatbot and authored content?
maybe at the bottom have some little note, or have a slight colour difference or something?

**Comment by FraserLee** [comment]
I'm going to work on this next. If anyone has a better place to look lmk, otherwise I'm just going to start at https://github.com/StampyAI/stampy-ui/blob/master/app/routes/questions/add.tsx#LL7C1-L14C2 and use the stampy codebase as a reference.

**Comment by FraserLee** [comment]
<img width="616" alt="Screenshot_2023-06-02_at_12 28 17_AM" src="https://github.com/StampyAI/stampy-chat/assets/30442265/c75b29e1-1326-4b51-af9f-b1250b745b9e">

**Comment by FraserLee** [comment]
I feel like https://github.com/StampyAI/stampy-ui/blob/master/app/server-utils/stampy.ts#L243-L252 is the function we need to expose via an API.

**Comment by ccstan99** [comment]
> I feel like https://github.com/StampyAI/stampy-ui/blob/master/app/server-utils/stampy.ts#L243-L252 is the function we need to expose via an API.

@Aprillion @mruwnik Thoughts on how you like to respond to the comment above?

**Comment by Aprillion** [comment]
@FraserLee luckily, that one _is_ exposed via API, using page id -> e.g. https://aisafety.info/questions/8486 

endpoint source code in https://github.com/StampyAI/stampy-ui/blob/master/app/routes/questions/%24question.tsx#L15-L39
