### ISSUE TITLE
Use new ARD

### ISSUE THREAD

**Issue by ccstan99** [StampyAI/stampy-chat#37]
The [updated dataset on HuggingFace](https://huggingface.co/datasets/StampyAI/alignment-research-dataset) should be ready in the next few days. The link contains documentation of different sources and keys. Some source names have changed but keys should more closely match the usage needed for the chatbot, so hopefully less error handling is needed now. You'll want to find a way to track id's which entries/documents have been embedded and which haven't, since our plan is to update these regularly.

Usage:
```sh
from datasets import load_dataset
data = load_dataset('StampyAI/alignment-research-dataset')
```

**Comment by Thomas-Lemoine** [comment]
PR #38

**Comment by FraserLee** [comment]
Does #39 close this?

**Comment by ccstan99** [comment]
Code is mostly there but still need to re-run embeddings. Waiting on a few more parts of ARD to be finalized.
