### ISSUE TITLE
Same citations in different questions will have different numbers

### ISSUE THREAD

**Issue by tayler6000** [StampyAI/stampy-chat#42]
A paper may be cited in two questions but with different citation numbers.  Ideally, it should reuse the number but have a link to citation below both questions.

![image](https://github.com/StampyAI/stampy-chat/assets/931092/90181671-ea30-4341-ac78-28c4fd08341e)

I am marking this as an enhancement instead of a bug because this may be a current limitation with the API.

**Comment by FraserLee** [comment]
This would be good, and doesn't need any API changes to pull off. Should be pretty easy, too. I ended up creating #46 after some initial investigation since there's some other work in this area we probably should be doing anyways, that would change how we go about implementing this.
