### ISSUE TITLE
Investigate Swap to GPT-4

### ISSUE THREAD

**Issue by FraserLee** [StampyAI/stampy-chat#47]
With falling API prices and rising importance of this project, I suspect this might now be possible. We should find the exact API costs of a message back and forth, work out some projected usage figures, and talk with Plex to see if it fits the org's budget.

**Comment by ccstan99** [comment]
Worth investigating & keeping an eye on this but main issue before was latency. Again, if we have a good baseline then we can compare quality of generated output.

**Comment by FraserLee** [comment]
I've used the new prompt-eng tooling I wrote to create a google sheet of answers comparing gpt-3.5-turbo to gpt-4. Imo the difference is so great that we have no choice but to switch, assuming the cost isn't prohibitively. I'm curious to know what others think
https://docs.google.com/spreadsheets/d/1vsaTHUVCBc0giH5UDD42R8eh2kMjvtQkIj9MKJMS5do/edit#gid=1376937604

**Comment by FraserLee** [comment]
I've created a benchmark to compare outputs from gpt-3.5-turbo-16k to gpt-4.  We'll need a handful of people to go through and rank their preferences.
https://forms.gle/P1RnHh5ziVJkgAi99

**Comment by ccstan99** [comment]
This is related to #34 so I'm going to close this as a duplicate.
