### ISSUE TITLE
Update stampy header

### ISSUE THREAD

**Issue by ccstan99** [StampyAI/stampy-chat#49]
- Add [stampy fun logo](https://github.com/StampyAI/StampyAIAssets/blob/main/profile/stampy-profile-228.png) or [minimal logo](https://github.com/StampyAI/StampyAIAssets/blob/main/stampy-ai-logo-min.svg)
- Bold title "Ask me a question about AI safety"
- Red warning: This is a very **early prototype** using data through June 2022. Please do not share this link widely. **Feedback** welcomed!
- Link feedback to https://bit.ly/stampy-chat-issues
- Change "Conversational Agent" and "Semantic Search" to "Chat" and "Search Sources"
- Can skip icons and other items for now

Use the image below as rough reference for layout but don't spend too much time matching the exact details since the UI design is still being finalized and will change.
<img width="1435" alt="Screenshot 2023-07-05 at 6 02 22 PM" src="https://github.com/StampyAI/stampy-chat/assets/38997995/f2386f6e-4007-42c4-9298-7e94b4778dca">

**Comment by FraserLee** [comment]
This might have come up in yesterday's meeting, but is the chat site personified like the discord bot? I was going off the impression we were keeping it in the style of http://aisafety.info/

**Comment by ccstan99** [comment]
It didn't come up. But currently the stampy.ai domain has the fun logo whereas aisafety.info is the more minimalistic one. Since we're currently only on chat.stampy.ai and it's mostly internal testing still, I just made a placeholder decision to start with the fun logo since it's generally more natural to be chatting with something that has a face. But we're in the process of rehauling the branding, communications, and UI/UX so everything is likely to change very shortly. Did you have an opinion you'd like to share?

**Comment by FraserLee** [comment]
I am a bit against the aesthetic of a smiling thing with a face since I worry it reads as a gimmick, leading our site to be dismissed prematurely instead of treated as a resource. The subtler face of https://aisafety.info would definitely be my preference here. Hard edges, clean design - instead of bubbles, clip art, and blue.

That said, that's not a very informed preference. We could totally go this way instead :)

**Comment by FraserLee** [comment]
I'll admit, It is a pretty fun logo.

**Comment by ccstan99** [comment]
> I am a bit against the aesthetic of a smiling thing with a face since I worry it reads as a gimmick, leading our site to be dismissed prematurely instead of treated as a resource. 

Understandable. That was our direction based on some initial feedback. But additional user responses and advice from the marketing & communications firm indicated that a face, if done properly, can be more memorable and have stronger emotional appeal. So it's something that we're still investigating.
