### ISSUE TITLE
Create web component

### ISSUE THREAD

**Issue by ccstan99** [StampyAI/stampy-chat#5]
The chat functionality should be encapsulated behind an API that can be called by frontend web apps, Discord bot, etc.
- Required params: query, chat history
- Optional params: top_k, temperature, user/language level, others?

**Comment by cvarrichio** [comment]
I'm curious - the core code is in a subdirectory called api.  Does this application already have some API capabilities I'm not aware of?

**Comment by ccstan99** [comment]
According to https://github.com/StampyAI/stampy-chat/blob/main/api/main.py, it looks like there are /chat and /semantic endpoints. The web app https://github.com/StampyAI/stampy-chat/blob/main/web/src/pages/index.tsx calls the $API_URL/chat endpoint. But ultimately, we should make the $API_URL available to the general public, so the functionality can be embedded into other apps and services as well.

**Comment by ccstan99** [comment]
As discussed in planning meeting, it was decided to provide chat capability as a web component rather than just API to allow for better support for streaming and citations features.

**Comment by FraserLee** [comment]
*To start with I'll clarify - we **do** have a communication scheme between the front and back end, and any alternate frontend is free to reimplement the protocol. When I say "API" in this context, I'm talking about standardizing and documenting what presently is encoded into the app itself, with the goal of making it externally replicable.*

### Reasons an API is a bad idea

1. Our user interaction story is inherently a bit complex. We ideally want to support a few types of engagement - straight conversation, but also suggested followup questions, quoted swampy database responses, etc.
2. *We don't want to maintain state on the server.* Stuff is overall a lot simpler if we can just have the client re-send the history with each request, turning the backend into a pure function. This makes for a far simpler app, but the communication protocol gets more complex.
3. We're also doing some kindof weird stuff. POST-request induced SSE. Not impossible someone else could get an alternate frontend working, but...
4. Any documentation that accurately captures these nuances would be of a similar level of complexity to the frontend code itself. Maintaining the both in parallel basically doubles our tech-dept and adds a lot of drag.

### What's the Solution?

From what we can tell, all that people really seem to want is to be able to host the front-end on their webpage. Style it in their own way, maybe do some light modifications, etc. They don't actually *need* a full API.

Instead I'll provide an alternate wrapping of the app as an unstyled web component, so people can embed it wherever, looking congruous with its environment. What's more, we can probably provide some decent JS callbacks when doing this - enabling *wayyyyy* easier custom functionality than implementing an entire alternative frontend. *If you'd like to embed it, please let me know the sorts of access-points you'd like.*

Lastly, for people who actually do need raw chat access, I've opened #18 so we can talk about ways that can work.

**Comment by FraserLee** [comment]
*this issue used to be about creating an API, ccstan has since renamed it :)*

**Comment by mruwnik** [comment]
this has pretty much been done, e.g. Discord also uses it
