### ISSUE TITLE
Stampy Chat seems to pull answers that aren't ready yet.

### ISSUE THREAD

**Issue by tayler6000** [StampyAI/stampy-chat#53]
Please ignore the Japanese, that's just a browser extension.

![](https://cdn.discordapp.com/attachments/1125882946952384635/1127704463872901151/image.png)

![](https://cdn.discordapp.com/attachments/1125882946952384635/1127704883143901215/image.png)

**Comment by FraserLee** [comment]
We're using the `https://nlp.stampy.ai/api/search?query=` endpoint - might want to ask people on the stampy side.

**Comment by ccstan99** [comment]
For the record, this was the [search to NLP endpoint](https://nlp.stampy.ai/api/search?query=Eliezer%20Yudkowsky%20and%20Paul%20Christiano%20have%20differing%20opinions%20on%20several%20aspects%20of%20AI.%20One%20key%20difference%20is%20their%20views%20on%20the%20potential%20impact%20of%20AI%20on%20humanity.%20Yudkowsky%20holds%20a%20more%20pessimistic%20view%2C%20seeing%20the%20development%20of%20AGI%20as%20a%20potential%20end-of-the-world%20scenario%20%5Bf%5D.%20He%20emphasizes%20the%20distinction%20between%20humans%20running%20as%20better%20robots%20and%20humans%20being%20replaced%20in%20the%20design-better-robots%20task%20%5Bf%2C%20g%5D.%20On%20the%20other%20hand%2C%20Christiano%20focuses%20on%20the%20idea%20of%20humans%20running%20as%20better%20robots%2C%20rather%20than%20being%20replaced%20in%20the%20design-better-robots%20task%20%5Bf%2C%20g%5D.%20He%20sees%20the%20evolutionary%20analogy%20as%20more%20relevant%2C%20where%20humans%20improve%20their%20capabilities%20rather%20than%20being%20completely%20replaced%20%5Bf%5D.%20%0A%0AAnother%20difference%20lies%20in%20their%20predictions%20about%20the%20speed%20of%20AI%20takeoff.%20Yudkowsky%20believes%20that%20AI%20progress%20could%20suddenly%20accelerate%20and%20lead%20to%20rapid%20development%2C%20potentially%20catching%20people%20by%20surprise%20%5Bg%5D.%20Christiano%2C%20on%20the%20other%20hand%2C%20holds%20a%20more%20gradualist%20view%2C%20expecting%20AI%20progress%20to%20continue%20at%20a%20steady%20rate%20%5Bb%5D.%0A%0AIt%27s%20worth%20noting%20that%20while%20they%20have%20different%20perspectives%2C%20they%20both%20acknowledge%20the%20challenges%20and%20difficulties%20in%20aligning%20AI%20systems%20with%20human%20values%20%5Bd%5D.%20They%20also%20agree%20on%20the%20importance%20of%20generating%20testable%20predictions%20to%20further%20understand%20the%20future%20of%20AI%20%5Bb%5D).

The Scratchpad entry status probably needs to be switched from "Live on site" to something else?
```
{
"id": "i-ae099e9aca3ec680876f5dfcc73f823ea391a5400e6dce1c804a3074d4504e581",
"pageid": "6315",
"score": 0.476089,
"status": "Live on site",
"title": "Scratchpad:TODO: How are current AIs intelligent compared to certain animals? ref https://www.lesswrong.com/posts/SFuLQA7guCnG8pQ7T/all-agi-safety-questions-welcome-especially-basic-ones-may?commentId=S97dfpcTJCvzbKXCc",
"url": ["https://aisafety.info?state=6315"](https://aisafety.info/?state=6315)
},
```

**Comment by ccstan99** [comment]
Oh, looking at the document (https://docs.google.com/document/d/1GkphSo2tQOTzkJwuyQI1uJ6op-A3Ld7ZUAfsHRMoBCM/edit) I think the scratchpad is being treated as an alternate phrasing for by parser. 
<img width="986" alt="Screenshot 2023-07-09 at 3 31 34 PM" src="https://github.com/StampyAI/stampy-chat/assets/38997995/fb09e154-2d89-449a-83df-f128c42b9c0d">

**Comment by ccstan99** [comment]
mruwnik fixed in gdocs parser to coda integration.
