### ISSUE TITLE
Investigate non essential cookies

### ISSUE THREAD

**Issue by Mishaall** [StampyAI/stampy-chat#63]
Investigate (non essential) cookies on saving settings, whether we’re trying to avoid tracking in general. (dont want to track for privacy reason).

**Comment by FraserLee** [comment]
We currently persist settings on reload with local storage, not cookies. I don't think it needs any legal disclosure since access is entirely client-side. Is there a reason the current solution isn't sufficient and that we would need cookies?

**Comment by ccstan99** [comment]
This question came up in the last meeting about keeping track of user settings for the level modes. Is that saved from session to session in local storage too?

**Comment by FraserLee** [comment]
Level modes are currently the only thing I save to local storage. Nothing else is persistent, and no cookies are used.
