### ISSUE TITLE
Inject glossary into generated answers

### ISSUE THREAD

**Issue by markovial** [StampyAI/stampy-chat#69]
Similar to the existing answers on stampy that utilize the glossary system, we should inject the glossary from [coda](https://coda.io/d/AI-Safety-Info_dfau7sl2hmG/Glossary_suZVl#_luIKu) or [gdocs](https://docs.google.com/document/d/1Rm7tN5zTErZq0E4qqAZoNVzClS94Kb_rQOLaViu2p6c/edit) into the generated answers.

This should save a whole bunch on tokens, because people would more often not need to ask a subsequent questions which then generate a couple of paragraphs worth of text.

[Here is an example](https://aisafety.info/?state=0_6953r6201r) of the current functioning glossary.

**Comment by FraserLee** [comment]
Does anyone know if the `https://aisafety.info/questions/glossary` endpoint currently would work for this?
