### ISSUE TITLE
Log all queries in MySQL

### ISSUE THREAD

**Issue by ccstan99** [StampyAI/stampy-chat#83]
Log all queries and generated answers run (on deployed server) to MySQL. Might as well include sources cited also. Maybe also include whether called from GUI or simplified API or anything else which will can help isolate and track potential abuses?

Some columns:
query: string with user query
chunks: list of pinecone ids of chunks
history: string or json/dict
prompt: string with full prompt
generated_answer: string
moderation: json/dict results of moderation if flagged, or all moderation even if not flagged?
thumbs_up: bool
thumbs_down: bool
comments: string for user to enter why thumbs down/up

**Comment by FraserLee** [comment]
The current webhook approach is pretty severely limited in bandwidth. If we were to do this, loads of other fun things would become possible even beyond the obvious security implications (dumping and logging complete prompts for replication, more automated and faster prompt eng work, etc).

**Comment by ccstan99** [comment]
Yes, my thoughts exactly!
